name: Hello World in Japanese

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: [self-hosted, dev, test]
    steps:
      - name: Say Hello
        run: echo "こんにちは世界"
