name: Hello for Bob

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: [self-hosted, bob]
    steps:
      - name: Hello Bob
        run: echo "こんにちは、ボブ"
